global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: rabbitmq
    static_configs:
      - targets: ["rabbitmq:15692"]

  - job_name: inventory-service
    metrics_path: "/metrics"
    static_configs:
      - targets: ["inventory-service:9464"]

  - job_name: order-fulfillment-service
    metrics_path: "/metrics"
    static_configs:
      - targets: ["order-fulfillment-service:9465"]

