services:
  rabbitmq:
    image: rabbitmq:3-management-alpine # Interfaz de gestión (alineado con día 8)
    container_name: eda_rabbitmq_dia09
    ports:
      - "5672:5672" # Puerto AMQP para la aplicación
      - "15672:15672" # Puerto para la interfaz de gestión web
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
volumes:
  rabbitmq_data:
